# application.properties
# spring.application.name=entertainment
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.url=jdbc:mysql://localhost:3306/entertainment?useSSL=false&serverTimezone=Asia/Seoul
# spring.datasource.username=gadget
# spring.datasource.password=5799
# spring.jpa.show-sql=true
# spring.jpa.hibernate.ddl-auto=none # create, update, validate, none
# spring.jpa.properties.hibernate.format_sql=true
# logging.level.org.springframework.security=debug


# application.yml
# Spring profiles
spring:
  profiles:
    include: jwt

  # Spring application name
  application:
    name: entertainment

  # Database connection
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/entertainment?useSSL=false&serverTimezone=Asia/Seoul
    username: gadget
    password: 5799

  # JPA configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #create, update, validate, none
      # naming:
        # physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true

# Logging configuration
logging:
  level:
    org.springframework.security: DEBUG # trace




